"""added genres to venue model

Revision ID: 910a77037d3a
Revises: e807839a1072
Create Date: 2020-12-24 12:28:43.798997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910a77037d3a'
down_revision = 'e807839a1072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
