"""empty message

Revision ID: dc8a233b60c4
Revises: 910a77037d3a
Create Date: 2020-12-24 16:04:01.446825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8a233b60c4'
down_revision = '910a77037d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue_description', sa.String(length=500), nullable=True))
    op.drop_column('artist', 'seeking_talent_description')
    op.add_column('venue', sa.Column('seeking_talent_description', sa.String(length=500), nullable=True))
    op.drop_column('venue', 'seeking_venue_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_venue_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_talent_description')
    op.add_column('artist', sa.Column('seeking_talent_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_venue_description')
    # ### end Alembic commands ###
